language: node_js
node_js:
- '4.1'
script: bash ./deploy.sh
env:
  global:
  - "-GH_REF": github.com/jvoigtlaender/elm-labyrinth
  - secure: Mdk+tokFeZ2rfLXrK2pHdbtDMpAexEt8uaTC2ZaGOV1RNn8d0MMkqZvXD4v+3kGHrYGm1G7VKEZC8XF5s5HAftIvv4MrLy0F13gY0nuXOjT8Gx/qm1I3ns5MYFK8H6V0v5rYheZotz/L6RF/oRkEzbpVsX0gz+0MwjQKnd9onRsh9fqoDs3kejBeetqC1drj1vX1rOtzsF6CO5tZeDV8SdW0hDXWy23E6Sb/Wx1UZmIsSvUjgn8NjSw2ZhP05TdufXBn/VAYHot+/5sWTBzwqH/3NI7uepBtM/prY10rr20q8GsFW3uyuyB4d9TvvDNUjNAOp6vVrg3TbQIF7UMDbO/bpboDMifxPykcAXb8pvNBmwbr0HBxAd/i9d/HlogNfWmwEvKvS9sp0P71Fq/FwNqM7OG4yOnYqZtsjSrMpmPchTq2QJaS966BX6ORMlfaWraLX/SMvlPcEf3q1ihHh3DDXbm/4McLThjuC3Nd5njWC6Ub0eULtL5mdxcU1M5aDOO903WJoS5ZAwhoU0gFY57ePhUSJIm0pvrJUjR+UTtrIDE/tjZ5OtOHs35cIaoCU5amsyb/JNk5xI7pkz1Sp1wBUv9OtXNjMzpn8tHEkRqYoYE/oM0DTeA4kwMZX0B18d15fXyPLwy7noCID7Cs6ZloeW3ImyRJ3fsL0BQIllk=
